name: Check, Lint

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-lint:
    name: Check, Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install latest nightly toolchain
        run: |
          rustup toolchain install nightly --component clippy,rustfmt
          rustup override set nightly

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Cargo check
        run: cargo check --all-targets --all-features

      - name: Clippy
        run: cargo clippy --all-targets --all-features
